@api= http://localhost:5070

GET {{api}}/api/customer

###
GET {{api}}/api/customers/1

###
POST {{api}}/api/customers
Content-Type: application/json

{}

###
PUT {{api}}/api/customers/1
Content-Type: application/json

{}

###
DELETE {{api}}/api/customers/1

###
GET {{api}}/api/product

###
GET {{api}}/api/products/1

###
GET {{api}}/api/products/available

###
POST {{api}}/api/product
Content-Type: application/json

{
    "Name" : "pens",
    "Description": "ink pens to write",
    "Price" : "20.00",
    "StockQuantity": 60,
    "IsAvailable": true
}


###
POST {{api}}/api/auth/register
Content-Type: application/json

{
    "Email" : "cust@gmail.com",
    "PasswordHash" : "1234"
}


###
POST {{api}}/api/auth/login
Content-Type: application/json

{
    "Email" : "cust@gmail.com",
    "PasswordHash" : "1234"
}


###
PUT {{api}}/api/products/1
Content-Type: application/json

{}

###
DELETE {{api}}/api/products/1