@api= http://localhost:5070

GET {{api}}/api/customer

###
GET {{api}}/api/customers/1

###
POST {{api}}/api/customers
Content-Type: application/json

{}

###
PUT {{api}}/api/customers/1
Content-Type: application/json

{}

###
DELETE {{api}}/api/customers/1

###
GET {{api}}/api/product

###
GET {{api}}/api/products/1

###
GET {{api}}/api/products/available

###
POST {{api}}/api/product
Content-Type: application/json

{
    "Name" : "pens",
    "Description": "ink pens to write",
    "Price" : "20.00",
    "StockQuantity": 60,
    "IsAvailable": true
}

###
PUT {{api}}/api/products/1
Content-Type: application/json

{}

###
DELETE {{api}}/api/products/1